const input = [
    [ 'number', 'number', 'number' ],  
    [ 'number', 'number', 'string' ],  
    [ 'number', 'number', 'boolean' ], 
    [ 'number', 'string', 'number' ],  
    [ 'number', 'string', 'string' ],  
    [ 'number', 'string', 'boolean' ], 
    [ 'number', 'boolean', 'number' ], 
    [ 'number', 'boolean', 'string' ], 
    [ 'number', 'boolean', 'boolean' ],
    [ 'string', 'number', 'number' ],  
    [ 'string', 'number', 'string' ],  
    [ 'string', 'number', 'boolean' ], 
    [ 'string', 'string', 'number' ],  
    [ 'string', 'string', 'string' ],  
    [ 'string', 'string', 'boolean' ], 
    [ 'string', 'boolean', 'number' ], 
    [ 'string', 'boolean', 'string' ], 
    [ 'string', 'boolean', 'boolean' ],
    [ 'boolean', 'number', 'number' ],
    [ 'boolean', 'number', 'string' ],
    [ 'boolean', 'number', 'boolean' ],
    [ 'boolean', 'string', 'number' ],
    [ 'boolean', 'string', 'string' ],
    [ 'boolean', 'string', 'boolean' ],
    [ 'boolean', 'boolean', 'number' ],
    [ 'boolean', 'boolean', 'string' ],
    [ 'boolean', 'boolean', 'boolean' ]
  ]
// dont touch /\
